[package]
name = "gantry-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
concurrent = []
durable = []

[dependencies]
gantry-core.workspace = true
gantry-host.workspace = true
gantry-ir.workspace = true

[lints]
workspace = true
