[package]
name = "gantry-adapter-tokio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
gantry-host.workspace = true
tokio = { workspace = true, features = ["rt", "time"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }

[lints]
workspace = true
